---
# tasks file for install_apache
- name: latest Apache version install
  yum:
    name: "{{ packages_to_install}}"
    state: latest
  tags:
    - cowsay
- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started
